#!/bin/bash

APPPATH="/home/bos/app/zj-bos.jar"
APPNAME=$(basename $APPPATH)
PROFILE="/home/bos/app/application-bos.yml"

#echo "This script runs $APPNAME as daemon"


start() {
  pid=$( ps -ef|grep $APPNAME|grep -v grep|awk {'print $2'} )
  if [ -n "$pid" ]; then
    echo -e "$APPNAME is \e[1;32m running \e[1;0m, pid is" $pid
    exit 1
  fi

  if [ -e "$APPPATH" ]; then
	if [ -e "$PROFILE" ]; then
		nohup java -jar -Dspring.config.location=$PROFILE $APPPATH 2>&1 |cat >/dev/null &
	else
		nohup java -jar $APPPATH 2>&1 |cat >/dev/null &
	fi	
  else
    echo -e "$APPPATH \e[1;35m not found \e[1;0m"
    exit 2
  fi
}

stop() {
  pid=$( ps -ef|grep $APPNAME|grep -v grep|awk {'print $2'} )
  if [ -n "$pid" ]; then
    kill -9 $pid
  else
    echo -e "$APPNAME is \e[1;35m not running \e[1;0m"
    exit 1
  fi
}

status() {
  pid=`ps -ef|grep $APPNAME|grep -v grep|awk {'print $2'}` 
  if [ -z $pid ];then
	echo -e "$APPNAME is \e[1;35m not running \e[1;0m"
  else
	echo "$APPNAME pid is" ${pid}
  fi
}

print_version() {
  $APPNAME -v
}


case "$1" in
  start)
    $1
    sleep 1
    status
    ;;
  stop)
    $1
    sleep 1
    status
    ;;
  restart)
    status
    stop
    sleep 1
    start
    sleep 1
    status
    ;;
  status)
    status
    ;;
  version)
    print_version
    ;;
  *)
    echo
    echo "Usage: $(basename "$0") (start|stop|restart|status)"
    echo
esac


exit 0

